@startuml swimlanes
participant "Client" as C #fdf2d0
participant "AS" as AS #d2e0e3
participant "RH" as RH #eececd
participant "RS" as RS #d8d3e7
C -[#0200f5]> AS: 1.

AS -[#0200f5]> RH: 2.

RH -[#48742c]> AS: 3.

AS -[#48742c]> RH: 4.

rnote over RH
  5.
end note

RH -[#48742c]> AS: 6.

RH -[#0200f5]> AS: 7.

AS -[#0200f5]> C: 8.
C -> AS: 9.
AS -[#48742c]> C: 10.
C -[#48742c]> RS: 11.
RS -[#48742c]> AS: 12.
AS -[#48742c]> RS: 13.
RS -[#48742c]> C: 14.
@enduml
