@startuml swimlanes
participant "Client" as C #fdf2d0
participant "Authorization Server (AS)" as AS #d2e0e3
participant "Resource Helper (RH)" as RH #eececd
participant "Resource Server (RS)" as RS #d8d3e7
C -[#0200f5]> AS: 1. Start standard code authorization grant
AS -[#0200f5]> RH: 2. Sub-flow for dynamic scope selection
rnote over RH
  Select fine-grained scope
end note
RH -[#0200f5]> AS: 3. Authorization Code for RH-API
AS -[#48742c]> RH: 4. Access RH-API
note over RH
   Scope info API
end note
RH -[#48742c]> AS: 5. Custom scope information
AS -[#0200f5]> C: 6. Authorization code callback (generic scopes param)
C -> AS: 7. Token request
note over AS
  Token endpoint
end note
AS -[#48742c]> C: 8. Token response
C -[#48742c]> AS: 9. Retrieve RS-specific client config (optional)
note over AS
  Scope Info API
end note
AS -[#48742c]> C: 10. Client config response
C -[#48742c]> RS: 11. Resource access request
note over RS
  Main resource API
end note
RS -[#48742c]> AS: 12. Token introspection request
AS -[#48742c]> RS: 13. Token introspection response
RS -[#48742c]> C: 14. Resource access response
@enduml
