version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: prismadb
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: secret
      TZ: UTC
      PGTZ: UTC
    ports:
      - 8888:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
